/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as KhataIndexRouteImport } from './routes/khata.index'
import { Route as KhataIdRouteImport } from './routes/khata.$id'
import { Route as SaleNewRouteImport } from './routes/sale.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const KhataIndexRoute = KhataIndexRouteImport.update({
  id: '/khata/',
  path: '/khata/',
  getParentRoute: () => rootRouteImport,
} as any)
const KhataIdRoute = KhataIdRouteImport.update({
  id: '/khata/$id',
  path: '/khata/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleNewRoute = SaleNewRouteImport.update({
  id: '/sale/new',
  path: '/sale/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/rates': typeof RatesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/khata/$id': typeof KhataIdRoute
  '/sale/new': typeof SaleNewRoute
  '/khata/': typeof KhataIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/rates': typeof RatesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/khata/$id': typeof KhataIdRoute
  '/sale/new': typeof SaleNewRoute
  '/khata': typeof KhataIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/rates': typeof RatesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/khata/$id': typeof KhataIdRoute
  '/sale/new': typeof SaleNewRoute
  '/khata/': typeof KhataIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/rates'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/khata/$id'
    | '/sale/new'
    | '/khata/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/rates'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/khata/$id'
    | '/sale/new'
    | '/khata'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/rates'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/khata/$id'
    | '/sale/new'
    | '/khata/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  RatesRoute: typeof RatesRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  KhataIdRoute: typeof KhataIdRoute
  SaleNewRoute: typeof SaleNewRoute
  KhataIndexRoute: typeof KhataIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khata/': {
      id: '/khata/'
      path: '/khata'
      fullPath: '/khata/'
      preLoaderRoute: typeof KhataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khata/$id': {
      id: '/khata/$id'
      path: '/khata/$id'
      fullPath: '/khata/$id'
      preLoaderRoute: typeof KhataIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale/new': {
      id: '/sale/new'
      path: '/sale/new'
      fullPath: '/sale/new'
      preLoaderRoute: typeof SaleNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  RatesRoute: RatesRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  KhataIdRoute: KhataIdRoute,
  SaleNewRoute: SaleNewRoute,
  KhataIndexRoute: KhataIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
